import { useClassProgress } from '../contexts/ClassProgressContext';

// ...existing code...

const handleSendMessage = async (userMessage: string) => {
  // ...existing code...
  
  addQueryToClass('Período Virreinal');
  
  // ...existing code...
};

// ...existing code...